### ISSUE TITLE
trim(_i) for extension of string arrays not working

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1301]
code:
SArr[] fillarray "a", "b", "c", "d"
trim_i SArr, 7
printarray(SArr)

result (Csound version 6.14 (double samples) Mar 12 2020):
 "a", "b", "c", "d", "(null)", "", "(null)"
Score finished in csoundPerform().
free(): invalid size
csound command: Aborted

for trim rather than trim_i i get:
PERF ERROR in instr 1 (opcode trim.k) line 66: Array too small (allocated 64 < needed 112), but cannot allocate during performance pass. Allocate a bigger array at init time
 from file /home/jh/Desktop/test2.csd (1)
	trim.k	SArr	7	
   note aborted
Score finished in csoundPerform().
csound command: Segmentation fault

i think for string arrays the new locations should be filled with an empty string.

**Comment by jpffitch** [comment]
Fixed trim_i

Now to look at trim.

**Comment by joachimheintz** [comment]
i pulled and tested but still the same error when using trim:

SArr[] fillarray "a", "b", "c", "d"
trim SArr, 7

PERF ERROR in instr 1 (opcode trim.k) line 56: Array too small (allocated 64 < needed 112), but cannot allocate during performance pass. Allocate a bigger array at init time
 from file /home/jh/Desktop/test2.csd (1)
	trim.k	SArr	7	
   note aborted

--Csound version 6.14 (double samples) Mar 18 2020
[commit: ead3622c22225e0479500a1e4a81e8756861493d]

**Comment by jpffitch** [comment]
That is the correc behaviour.  It was decided after many emais that there 
should not be any memory allocation at perf time for arrays.  7 is larger 
than 4 so it is an error.

trim_ works at i-tie where tere is no such restriction.

==John

**Comment by joachimheintz** [comment]
understood, but it is not written in the manual.  instead:

" Makes the array the desired length, either truncating or padding with 
zero/Null values. "

i will mention it in my text about arrays.
