### ISSUE TITLE
New host API, compile_csd() issues in ctcsound 

### ISSUE THREAD

**Issue by mesca** [csound/csound#1916]
I am testing the new ctcsound lib from the [feature/newapi](https://github.com/csound/csound/tree/feature/newapi) branch.

According to the inline [documentation](https://github.com/csound/csound/blob/3e734ce39342cc3f63b519586feaf1079c841055/Python/ctcsound.py#L738-L780), the following should work:

```python
cs.set_option("-odac")
cs.start()
cs.compile_csd("test.csd", 0)
```

But there is no sound, the performance ends immediately, and I get the following output (irrelevant lines removed for clarity):

```
sr = 44100.0, kr = 4410.000, ksmps = 10
PortAudio: selected output device 'MacBook Air Speakers'
Skipping <CsOptions>
WARNING: system constants can only be set once
Score finished in csoundPerformKsmps() with 2.
```

The following works as expected:

```python
cs.compile_csd("test.csd", 0)
cs.start()
```

```
sr = 48000.0, kr = 750.000, ksmps = 64
```

But compiling a CSD string directly does not:

```python
cs.compile_csd(csd, 1)
cs.start()
```

```
sr = 44100.0, kr = 4410.000, ksmps = 10
WARNING: Output file already exists: Will be overwritten.
writing 2048-byte blks of shorts to test.aif (AIFF)
```

Options are ignored. Note that `test.aif` did not already exist. The output file grows as the performance continues, but does not contain any audible sound. Calling `set_option("-odac")` before `compile_csd(csd, 1)` removes the output file messages, but there is no sound. 

I'm using the following simple CSD for testing purposes:

```csound
<CsoundSynthesizer>

<CsOptions>
-odac
</CsOptions>

<CsInstruments>

sr = 48000
ksmps = 64
nchnls = 2
0dbfs  = 1

instr Test
    k_freq = p4
    k_amp = p5
    a_sig = poscil(k_amp, k_freq)
    out(a_sig)
endin

</CsInstruments>
<CsScore>

i "Test" 0 -1 440 .2

e 1e6 ; Run (nearly) forever

</CsScore>
</CsoundSynthesizer>
```

@fggp

**Comment by vlazzarini** [comment]
The problem is the line in the score

```
e 1e6 ; Run (nearly) forever
```
It is not doing what you think it should do. There are two cases:

(1) The CSD is compiled before csoundStart()

In this case, the CSD is compiled as usual, and the CsScore section gives the numeric score to control the performance, when it runs out, Csound stops. In this case the "e" score line is read as giving the end of the score at p1 time.

(2) CsoundStart() starts Csound before any code whatsoever is compiled, and more importantly here, no score is given. In this case two things happen: Csound runs forever by default (since there is no score to control when it should stop); and the CsScore section is read for realtime events that should be played.
The problem is that an "e" realtime event will stop Csound dead in its tracks. So that's the behaviour you are getting (this is a known thing but since not many people use "e" in realtime, it is also not well documented,
but may be related to https://github.com/csound/csound/issues/1689, which was believed fixed).

I tested your examples removing the offending line and replacing it by `f 0 z` which does the same thing for a compiled CSD (pre-start)

```
<CsScore>
f 0 z
i "Test" 0 -1 440 .2
</CsScore>
```
So we can follow this up on that issue (maybe?), and close this one.

**Comment by vlazzarini** [comment]
This is fixed in 92a51fc4062fd7cf92bf12a08ea189ab3b5554b3

**Comment by mesca** [comment]
Thank you, this solves the problem of the performance ending prematurely. Unfortunately, the other issues are still present on the latest commit. Here are some test cases (the content of `test.csd` is the same as the `csd` variable):

```python
import ctcsound
cs = ctcsound.Csound()

csd = '''
<CsoundSynthesizer>

<CsOptions>
-odac
</CsOptions>

<CsInstruments>

sr = 48000
ksmps = 64
nchnls = 2
0dbfs  = 1

instr Test
    k_freq = p4
    k_amp = p5
    a_sig = poscil(k_amp, k_freq)
    out(a_sig)
endin

</CsInstruments>
<CsScore>

f 0 z
i "Test" 0 -1 440 .2

</CsScore>
</CsoundSynthesizer>
'''

# CASE 1 (KO): no sound, warnings
# -------------------------------
cs.set_option("-odac")
cs.start()
cs.compile_csd("test.csd", 0)

# CASE 2 (OK)
# -----------
# cs.compile_csd("test.csd", 0)
# cs.start()

# CASE 3 (KO): options are ignored
# --------------------------------
# cs.compile_csd(csd, 1)
# cs.start()

# CASE 4 (KO): no sound
# ---------------------
# cs.set_option("-odac")
# cs.compile_csd(csd, 1)
# cs.start()

# CASE 5 (KO): no sound
# ---------------------
# cs.set_option("-odac")
# cs.start()
# cs.compile_csd(csd, 1)

while True:
    if cs.perform_ksmps():
        break
cs.reset()

```

**Comment by vlazzarini** [comment]
Check your options. If you are running with 0dbfs=1 you need to set these before csoundStart(). You will get no audible sound if 0dbfs is wrong.  I tested all cases here, setting options correctly and it works.

So: CSD sent in before csoundStart() will take options from CsOptions, after that ALL options and global settings (sr, etc) are ignored.

**Comment by vlazzarini** [comment]
C code

CSD text after CsoundStart()

```
#include <stdio.h>
#include <CsoundLib64/csound.h>

int main(int argc, char **argv) {

  CSOUND  *csound;
  const char *code = R"ORC(
<CsoundSynthesizer>

<CsOptions>
</CsOptions>

<CsInstruments>

instr Test
    k_freq = p4
    k_amp = p5
    a_sig = poscil(k_amp, k_freq)
    out(a_sig)
endin

</CsInstruments>
<CsScore>
i "Test" 0 -1 440 .2
e 1e6 ; Run (nearly) forever
</CsScore>
</CsoundSynthesizer>
   )ORC";

  csound = csoundCreate(NULL, NULL);
  csoundSetOption(csound, "-odac");
  csoundSetOption(csound, "--nchnls=2");
  csoundSetOption(csound, "--ksmps=64");
  csoundSetOption(csound, "--0dbfs=1");
  csoundStart(csound);
  csoundCompileCSD(csound, code, 1);
  while(csoundPerformKsmps(csound) == 0);
  csoundDestroy(csound);
  return 0;
}
```

CSD text before CsoundStart()

```
#include <stdio.h>
#include <CsoundLib64/csound.h>

int main(int argc, char **argv) {

  CSOUND  *csound;
  const char *code = R"ORC(
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>

<CsInstruments>
nchnls = 2
ksmps = 64
0dbfs=1

instr Test
    k_freq = p4
    k_amp = p5
    a_sig = poscil(k_amp, k_freq)
    out(a_sig)
endin

</CsInstruments>
<CsScore>
i "Test" 0 -1 440 .2
e 1e6 ; Run (nearly) forever
</CsScore>
</CsoundSynthesizer>
   )ORC";

  csound = csoundCreate(NULL, NULL);
  csoundCompileCSD(csound, code, 1);
  csoundStart(csound);
  while(csoundPerformKsmps(csound) == 0);
  csoundDestroy(csound);
  return 0;
}
```
CSD file after CsoundStart()

```
int main(int argc, char **argv) {

  CSOUND  *csound;
  const char *code = "testcsd.csd";

  csound = csoundCreate(NULL, NULL);
  csoundSetOption(csound, "-odac");
  csoundSetOption(csound, "--nchnls=2");
  csoundSetOption(csound, "--ksmps=64");
  csoundSetOption(csound, "--0dbfs=1");
  csoundStart(csound);
  csoundCompileCSD(csound, code, 0);
  while(csoundPerformKsmps(csound) == 0);
  csoundDestroy(csound);
  return 0;
}
```

CSD file before CsoundStart()

```
#include <stdio.h>
#include <CsoundLib64/csound.h>

int main(int argc, char **argv) {

  CSOUND  *csound;
  const char *code = "testcsd.csd";
  csound = csoundCreate(NULL, NULL);
  csoundStart(csound);
  csoundCompileCSD(csound, code, 0);
  while(csoundPerformKsmps(csound) == 0);
  csoundDestroy(csound);
  return 0;
}
```

**Comment by mesca** [comment]
Oh, of course, setting `cs.set_option("--0dbfs=1")` if the csd is compiled before `start()` makes complete sense 🤦. This fixes my first use case, although the warnings ("_system constants can only be set once_") are still there. 

It's great to see that your C example (_CSD text before CsoundStart()_) works, but unfortunately, it seems to be broken in Python.

So, in summary, these two examples (inline CSD) do not work with the Python API (the options are ignored in both cases):

```python
cs.compile_csd(csd, 1)
cs.start()
```

```python
cs.set_option("-odac")
cs.set_option("--nchnls=2")
cs.set_option("--ksmps=64")
cs.set_option("--0dbfs=1")
cs.start()
cs.compile_csd(csd, 1)
```

This seems to be an issue in ctcsound and not the C API. Maybe @fggp can have a look?

**Comment by vlazzarini** [comment]
I've reopened but I still think it's an issue with code call sequence. I'll let @fggp check the python wrapper, my C code is there as a reference.

Regarding the warning, that will always happen if you try to set sr etc from your code after CsoundStart().

**Comment by fggp** [comment]
That was a subtle bug!

From ctcsound.py, when invoking compile_csd, the old API csoundCompileCsd
function was called instead of the new one csoundCompileCSD. Fixed now in
github.

Anyway, when using one of the compile_... methods, I think it is good
practice  to test the returned error value before further processing...

Regards

François

**Comment by mesca** [comment]
Everything work as expected, now. Thanks!
