### ISSUE TITLE
Compiling orchestra with unterminated macro definition causes crash

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#542]
When using Csound’s API, compiling an orchestra that contains an unterminated macro definition appears to cause a crash on OS&nbsp;X. Here is a code example illustrating the issue:

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileOrc(Csound, "#define FOO #BAR\n");
    return 0;
}
```

I’m only able to produce this using `csoundCompileOrc`. Compiling, from the command line, an orchestra file containing

```
#define FOO #BAR
```

doesn’t appear to produce a crash.

**Comment by nwhetsell** [comment]
This is probably a related issue; using `csoundCompileOrc` to compile the string `"#define"` also appears to cause a crash.

**Comment by nwhetsell** [comment]
In a similar vein, using `csoundCompileOrc` to compile the string `"$MACRO"` also appears to cause a crash.

**Comment by vlazzarini** [comment]
thanks, we will have a look at these and make sure Csound exits cleanly.

**Comment by nwhetsell** [comment]
Many thanks.

I’ve also found that using `csoundCompileOrc` to compile the string `"/*"` appears to cause a crash. I can open this as a separate issue if you’d prefer, but I’m guessing these all have the same root cause.

**Comment by vlazzarini** [comment]
it looks that way. Thanks for reporting it.

**Comment by jpffitch** [comment]
Version in git gives error message "unexpected EOF" and then crashes on exit.  Do you get the message?

**Comment by jpffitch** [comment]
The crash is because there is no longjmp set up in csound structure  so it jump into the void.

(this is in git version) so an API issue and not my department to coin a phrase

**Comment by nwhetsell** [comment]
Yes, when Csound crashes, my Xcode console contains

```
virtual_keyboard real time MIDI plugin for Csound
Error: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
Csound version 6.05 (double samples) Jun  8 2015
libsndfile-1.0.25
unexpected EOF
```

`unexpected EOF` also appears when I compile an orchestra file containing

```
#define FOO #BAR
```

from the command line. Csound’s exit code is 255.

**Comment by jpffitch** [comment]
In wich case it is the lack of a setjmp in the sound structure, so I could 
say it is user error, or needs a default to call exit

**Comment by nwhetsell** [comment]
Not being a Csound developer, I’m afraid I don’t know what it means for there to be a “lack of a setjmp in the sound structure”. If you can link to some documentation or code, I’m happy to take a look.

While `"#define FOO #BAR\n"` is not a valid orchestra, I’m actually trying to use Csound’s API to compile orchestras being edited in a text editor; I don’t control what the orchestras contain, and when Csound crashes it takes the editor with it. While editing, if one wants to type a new macro in a previously valid orchestra, one can type “#define”, and then `csoundCompileOrc` crashes. In any case, it doesn’t seem like expected behavior for `csoundCompileOrc` to crash when given strings like `"#define FOO #BAR\n"` and `"/*"`.

**Comment by vlazzarini** [comment]
We need to add a destination for the longjmp.

**Comment by jpffitch** [comment]
Fixed in git

**Comment by nwhetsell** [comment]
I still see a crash in `do_comment` when passing `"/*"` to `csoundCompileOrc`. If preferred, I can open this as a new issue.

**Comment by jpffitch** [comment]
Works for me; can you provide an example?

**Comment by nwhetsell** [comment]
```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileOrc(Csound, "/*");
    return 0;
}
```

Here’s a screenshot of Xcode stopped at the crash:

<img width="1512" alt="screen shot 2015-10-29 at 12 56 00 pm" src="https://cloud.githubusercontent.com/assets/14102861/10825676/7b24ddc2-7e3c-11e5-95a2-9a09e7804252.png">

**Comment by jpffitch** [comment]
Works for me

birtwistle:~/Sourceforge/csound/New/csound6> a.out
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.06 (double samples) Oct 24 2015
libsndfile-1.0.26pre6
unexpected EOF
end of score.              overall amps:      0.0
            overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.000s, CPU: 0.000s

**Comment by nwhetsell** [comment]
No such luck here. Even compiling a file containing just `/*` from a Terminal using

```sh
csound --syntax-check-only --orc Test.orc
```

results in

```
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.06 (double samples) Oct 29 2015
libsndfile-1.0.25
orchname:  Test.orc
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled

csound command: Segmentation fault
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.253s, CPU: 0.001s
```

**Comment by vlazzarini** [comment]
I can confirm it crashes here on OSX too.

**Comment by vlazzarini** [comment]
I think this is not the same issue as before, as the csound CLI program is also crashing.

**Comment by nwhetsell** [comment]
Should I close this issue and open a new one for crashing with unclosed block comments?

**Comment by jpffitch** [comment]
Looking at the xcode screen shot this is not t he code presented as the bug.  I have 
#include "csound.h"

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileOrc(Csound, "/*");
    csoundCleanup(Csound);
    return 0;
}

What is the broken example?   Note I do not know about xcode --- I need simple text

**Comment by nwhetsell** [comment]
Based on the code in your comment, it looks like you’re passing the wrong string (`"/"`) to `csoundCompileOrc`, although it’s difficult to tell because [Markdown](https://help.github.com/articles/github-flavored-markdown/) italicizes text between asterisks, so a `*` may have gotten lost in what you wrote. If you’re trying to reproduce this issue on OS&nbsp;X, you should pass `"/*"` to `csoundCompileOrc` as in the example I gave in https://github.com/csound/csound/issues/542#issuecomment-152248428:

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileOrc(Csound, "/*");
    return 0;
}
```

If you want it simpler, you can reduce that to one line:

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    return csoundCompileOrc(csoundCreate(NULL), "/*");
}
```

The Xcode screenshot contains an explanation of why the code is different: “to show that the most recent version of Csound from GitHub is being used.” Before October&nbsp;29, Csound would crash at the call to `csoundCompileOrc` at line&nbsp;7 of the code in that screenshot, not the one at line&nbsp;17.

Note that this issue may only be reproducible on OS&nbsp;X according to https://github.com/csound/csound/issues/542#issuecomment-152255069. Please note also that I’m no longer able to devote time to this issue. If this is indeed a bug, Csound’s contributors might be better off creating a [CTest](https://cmake.org/Wiki/CMake/Testing_With_CTest) test case for it.

**Comment by jpffitch** [comment]
The string in my code is "/*" with the  asterisk.  Markdown is making this issue system a problem.  Can one not turn it off?


I was looking at Victor's backtrace and it does not correspond to my sources so was wondering.

Not sure what ctest has to do with it

**Comment by fsateler** [comment]
@jpffitch you can turn it off for a block, by issuing three consecutive backticks, pasting your code, and then three consecutive backticks again.

    ```
    this will be formatted as code
    ```

**Comment by vlazzarini** [comment]
Crashing in the same place
```
lldb) bt
* thread #1: tid = 0x2004f, 0x00007fff94a88c67 libsystem_c.dylib`flockfile + 4, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x68)
  * frame #0: 0x00007fff94a88c67 libsystem_c.dylib`flockfile + 4
    frame #1: 0x00007fff94a8a9df libsystem_c.dylib`fread + 31
    frame #2: 0x00000001002bf1f8 CsoundLib64`yy_get_next_buffer(yyscanner=0x0000000101156e60) + 1496 at csound_prelex.c:2276
    frame #3: 0x00000001002bc196 CsoundLib64`input(yyscanner=0x0000000101156e60) + 182 at csound_prelex.c:2443
    frame #4: 0x00000001002bbbac CsoundLib64`do_comment(yyscanner=0x0000000101156e60) + 28 at csound_pre.lex:688
    frame #5: 0x00000001002b7585 CsoundLib64`csound_prelex(csound=0x0000000100807800, yyscanner=0x0000000101156e60) + 1909 at csound_pre.lex:201
    frame #6: 0x00000001002d6fda CsoundLib64`csoundParseOrc(csound=0x0000000100807800, str="/*") + 1194 at new_orc_parser.c:183
    frame #7: 0x00000001002d57f5 CsoundLib64`csoundCompileOrc(csound=0x0000000100807800, str="/*") + 181 at csound_orc_compile.c:1763
    frame #8: 0x0000000100000f46 bug`main(argc=1, argv=0x00007fff5fbff8f8) + 54 at bug.c:5
    frame #9: 0x00007fff974ad5c9 libdyld.dylib`start + 1
    frame #10: 0x00007fff974ad5c9 libdyld.dylib`start + 1
```

**Comment by vlazzarini** [comment]
I can get the same effect with the csound command the following CSD
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
/*

</CsInstruments>
<CsScore>
i1 0 1
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
So either OSX has a broken flex or the charcater code issue is biting

**Comment by vlazzarini** [comment]
I was looking at the same place, line 688. Can't find a problem.

**Comment by vlazzarini** [comment]
But I think the problem is in line 689 and the macro calling fread().

**Comment by vlazzarini** [comment]
and this is the macro definition where fread() is called:
```
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif
```

**Comment by jpffitch** [comment]
I will look at prepaing a tracing version of do_comment and send it ti 
you, as well as Linux output fro same.
   It does indeed behave the same in commandline mode -- ie gives error 
message -- on Linux.

**Comment by jpffitch** [comment]
I have committed a fixed version, totally rewriten

**Comment by vlazzarini** [comment]
I can confirm it works here.

**Comment by jpffitch** [comment]
I would like to leave it open for a short while as it is so different that I may have got the FSM wrong.  Still not sure what I expect if the /* is in a #include file and the comment is terminated in the caller.....

**Comment by jpffitch** [comment]
It is now seriously broken --- exampleabo.csd from the manual fails!  Just a simple /* */ comment.

**Comment by jpffitch** [comment]
Fixed the silly errorl cosing issue
