### ISSUE TITLE
Add support for Jack midi

### ISSUE THREAD

**Issue by genell** [csound/csound#559]
Although the Jacko opcodes exist, having Jack midi support as in -+rtmidi=jack would make life simpler for users of jack-aware midi controllers/sequencers.

**Comment by vlazzarini** [comment]
started this today, and added code for midi input. Completely untested yet (not sure if it even works).
But we're on our way.

**Comment by genell** [comment]
Great, thanks!!
I'll pull and test on my Linux box tomorrow to see what happens so far...

Regards
Anders

**Comment by vlazzarini** [comment]
I don't even know if it does anything. The string argument passed to -M should be the name of
the MIDI source port.

**Comment by genell** [comment]
Hm, it doesn't seem to build properly for me:

[ 60%] Building C object
Opcodes/CMakeFiles/jackTransport.dir/jackTransport.c.o
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libjack.so',
needed by `libjackTransport.so'.  Stop.
make[1]: *** [Opcodes/CMakeFiles/jackTransport.dir/all] Error 2
make: *** [all] Error 2

Could that be related to the rtmidi changes?
Should I add something to the cmake settings somehow?

Regards,
Anders

**Comment by vlazzarini** [comment]
looks like you don't have jack installed?

/usr/lib/x86_64-linux-gnu/libjack.so

is the jack library

**Comment by vlazzarini** [comment]
or at least the jack devel library, maybe? libjack-dev

**Comment by genell** [comment]
Hm. You might be right...
But I also saw "-- BUILD_JACK_OPCODES is enabled" in the cmake output which
led me to believe it was already there...
I'll check...

**Comment by gogins** [comment]
Sounds like you need to install the Dec package for jack.

Regards,
Mike

**Comment by genell** [comment]
Ok, found it - cmake/make was looking in /usr/lib/x86_64-linux-gnu but as I
(for some long since forgotten reason) have built jack from source, they
were in /usr/local/lib64/.
Now all is well ([100%] Built target translations).

Thanks!
Regards,
Anders

**Comment by genell** [comment]
"It's... ALIVE!!"

csound-midi shows up in the Qjackctl midi connection window, I can hook the
jack-keyboard to it and trigger intrument instances using the 'virtual.csd'
csound manual example file adopted to -+rtmidi=jack.
It seems slightly intermittent in reacting to key presses, but whether that
is due to the new jack midi code or some instability in my system (or the
example csd file) I dare not say.

I'll continue to tinker with it...

Thank you Victor!!

Regards,
Anders

**Comment by genell** [comment]
Update:

I can also get csound to connect to the jack-keyboard by:
-+rtmidi=jack -M jack-keyboard:midi_out

**Comment by genell** [comment]
Update:

I am gettig a lot of
WARNING: MIDI note overlaps with key 48 on same channel
if pressing the same key more than once, or more than twice actually since
it seems to register every other key press...

**Comment by genell** [comment]
Update:

There is definately something fishy...
There seem to be no note off received, and only some of the key presses are
registered.
the 'midiin' opcode with four output variables prints the following when
pressing the same key several times:

graphics suppressed, ascii substituted
0dBFS level = 32768.0
chnl 1 using instr 1
orch now loaded
audio buffered in 256 sample-frame blocks
system sr: 48000.000000
 0: dac:system:playback_ (system:playback_)
writing 512 sample blks of 64-bit floats to dac
SECTION 1:
  rtevent:   T  4.907 TT  4.907 M:      0.0      0.0
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000

[after this first key press, several presses were ignored]

  rtevent:   T 13.483 TT 13.483 M:      0.0      0.0
WARNING: MIDI note overlaps with key 60 on same channel
 i1   144.00000
 i1     1.00000
 i1    60.00000
 i1    64.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
  rtevent:   T 20.443 TT 20.443 M:      0.0      0.0
WARNING: MIDI note overlaps with key 60 on same channel
 i1   144.00000
 i1   144.00000
 i1     1.00000
 i1    60.00000
 i1    64.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
  rtevent:   T 25.051 TT 25.051 M:      0.0      0.0
WARNING: MIDI note overlaps with key 60 on same channel
 i1   144.00000
 i1   144.00000
 i1   144.00000
 i1     1.00000
 i1    60.00000
 i1    64.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     0.00000

**Comment by gogins** [comment]
Sounds like a bug.

Conceptually, MIDI notes are not single events, each note is one NOTE ON
event followed by one NOTE OFF event for that channel and key number. This
concept obviously has a lot of problems. If two NOTE ON events come in for
a channel and key, then the implementer has a choice when the first NOTE
OFF comes in for that channel and key: turn off both notes, or turn off one
and wait for another NOTE OFF for the channel and key to turn the second
NOTE ON off.

In other words, MIDI has no concept of a "note" in any recognizable musical
sense. MIDI only knows about "performance gestures" such as pressing a key.

This becomes a problem when not physical devices, but software starts to
emit MIDI messages. A keyboard can't send a second NOTE ON for the same key
until that key is first released thus sending a NOTE OFF, so all the NOTE
ON and NOTE OFF events match. But software can and does easily do that.

Again, the implementer has to decide how to handle multiple overlapping
"notes". One choice is to simply turn off all NOTE ON for a channel and
key, no matter how many are pending, when one NOTE OFF comes in for that
channel and key, then ignore subsequent NOTE OFF events for that channel
and key. Another choice is to maintain a pushdown stack for each channel
key. NOTE ON pushes a note on the stack, NOTE OFF pops a note off the
stack. Both approaches can work but obviously both approaches have little
to do with whatever notes might appear on a score or in a list of real
notes. For example, if a note list contains a long note for a channel and
key and then a short note that starts and ends within the long note, then
when a NOTE OFF comes in the first approach turns both notes off even
though the musician intended the first note to continue, and the second
approach does what the musician intends. But then the software has to know
enough to go through all the stacks for each channel and key combination
and turn off any pending notes when performance ends for any reason.

HOWEVER, this all may be beside the point because after reading your
message again, it sounds like the problem is really the well known
ambiguity that a NOTE OFF can be signaled by an actual NOTE OFF event,or by
a NOTE ON event with a velocity of zero. Sounds like the code was written
only for the first case but the hardware or MIDI system is presenting the
second case, and furthermore doesn't allow overlapping notes but turns off
a pending note when another NOTE ON for it comes in.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by genell** [comment]
I'm beginning to understand why OSC came about... :-)
Anyway, I am just using the jack virtual keyboard (jack-keyboard) to test
things, and it has worked fine with jack aware synths like QSynth, so I
suppose there is a way to implement this.
Actually, just now I did get note off (128) messages too, after having had
the csound instance running for some time, so there might be something
strange going on with how messages are received...

Well, as Victor said, he hasn't tested it at all, so for a first test I'd
say this is very successful!

Does the Jacko opcodes contain any black (or other) magic to handle
messages?
Is it perhaps the strict ksmps requrements ("The control rate must be BOTH
a power of 2 (for Jack) AND go evenly into sr.") of those opcodes that
might be lacking in the rtmidi implementation?
Why DOES control rate need to both be power of two and go evenly into sr?

Regards,
Anders

**Comment by gogins** [comment]
Currently, the Jacko opcodes not use buffer queues and do not allow for
overlapping buffers. Implementing these would be possible but at the cost
of some additional complexity.

Currently, each Jack callback produces and consumes exactly one buffer from
each side. That involves fixed length audio buffers and variable length
MIDI buffers. Pthreads condition variables switch back and forth between
Csound and Jack as the buffers are produced and consumed.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
Hi @genell, thanks for testing this. I was actually predicting these hickups. I was trying to implement in
the simplest way possible, but I think it needs some adjustments. I am actually glad you got messages
through. I'll try and fix these things and let you know when I am done.

**Comment by genell** [comment]
Thanks, Victor!
I look forward to it - please let me know if there are any specific tests
you want me to do (like Dr Lazzarini's World Famous 'I went all Cecil
Taylor on it'-test)!

Regards
Anders

**Comment by vlazzarini** [comment]
I love Cecil Taylor.

**Comment by genell** [comment]
Thanks for the explanation, Mike!
I suppose that is similar to what one would (could) do if writing a custom
software using the csound api, and calling performKsmps() to keep buffers
in sync with other parts of the program, as suggested in som other email
discussions?
I don't do much programming, but I do like to understant how things work :-)

Regards,
Anders

**Comment by genell** [comment]
Not only is his music great, it provides excellent test cases - a true
renaissance man!

Since gmail provides an almost infinite mail archive, I found you used the
Cecil Taylor test on February 2:nd 2013:
" I can force a crash when using both csoundqt midi and coremidi, if I
overload the system with messages (going Cecil Taylor on the keyboard)."

I don't know what the fact that that line stuck in my brain for neigh on
two years says about me other than that I should probably work on
remembering things I actually need to, like where the house keys are or
where I parked my bike. Oh, well.

Regards,
Anders

**Comment by vlazzarini** [comment]
Very true. I forgot about that message. Anyway, I've changed the implementation to
something more sensible, using a process callback. You can try to see if it works.
If it doesn't, I'll go back to the drawing board.

**Comment by genell** [comment]
Just quick followup (while the food is getting cold):

All my csd does is:
massign 1,1
prealloc 1,10

instr 1

        kstatus, kchan, kdata1, kdata2 midiin
        printk2 kstatus
        printk2 kchan
        printk2 kdata1
        printk2 kdata2

endin

and when pressing and releasing one key while keeping another pressed I get:

  rtevent:   T 47.211 TT 47.211 M:      0.0      0.0
 i1   144.00000
 i1    74.00000
 i1     0.00000
 i1     1.00000
 i1    64.00000
 i1    64.00000
 i1     0.00000
  rtevent:   T 48.245 TT 48.245 M:      0.0      0.0
 i1   128.00000
 i1     0.00000

Dont't know if that adds up to a correct sum of events and prints...?

Regards,
Anders

**Comment by vlazzarini** [comment]
although it's hard to read, that's what I get here too with a different MIDI backend (e.g. CsoundQT),
so in principle, it might be correct.

**Comment by vlazzarini** [comment]
Try this instrument:
```
massign 0,0
instr 1
 kstatus, kchan, kdata1, kdata2 midiin
 printf "MESS:%d,CHAN:%d,DB1:%d,DB2:%d\n",kstatus,kstatus,   kchan,kdata1,kdata2
endin
schedule(1,0,-1)
```

**Comment by genell** [comment]
Here's the output using your instrument and just doing a quick sweep over
the keys with the mouse pointer:

$ csound checkmidi.csd
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.07 (double samples) Nov 30 2015
libsndfile-1.0.25
UnifiedCSD:  checkmidi.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: JACK module enabled
rtmidi: JACK module enabled
Elapsed time at end of orchestra compile: real: 0.002s, CPU: 0.002s
sorting score ...
... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.002s
--Csound version 6.07 (double samples) Nov 30 2015
midi channel 1 using instr 1
midi channel 2 using instr 1
midi channel 3 using instr 1
midi channel 4 using instr 1
midi channel 5 using instr 1
midi channel 6 using instr 1
midi channel 7 using instr 1
midi channel 8 using instr 1
midi channel 9 using instr 1
midi channel 10 using instr 1
midi channel 11 using instr 1
midi channel 12 using instr 1
midi channel 13 using instr 1
midi channel 14 using instr 1
midi channel 15 using instr 1
midi channel 16 using instr 1
graphics suppressed, ascii substituted
0dBFS level = 32768.0
MIDI channel 1 muted
MIDI channel 2 muted
MIDI channel 3 muted
MIDI channel 4 muted
MIDI channel 5 muted
MIDI channel 6 muted
MIDI channel 7 muted
MIDI channel 8 muted
MIDI channel 9 muted
MIDI channel 10 muted
MIDI channel 11 muted
MIDI channel 12 muted
MIDI channel 13 muted
MIDI channel 14 muted
MIDI channel 15 muted
MIDI channel 16 muted
orch now loaded
audio buffered in 256 sample-frame blocks
system sr: 48000.000000
 0: dac:system:playback_ (system:playback_)
writing 256 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
  rtevent:   T  4.560 TT  4.560 M:      0.0
MESS:144,CHAN:1,DB1:37,DB2:64
  rtevent:   T  4.715 TT  4.715 M:      0.0
MESS:128,CHAN:1,DB1:37,DB2:64
MESS:144,CHAN:1,DB1:38,DB2:64
  rtevent:   T  4.723 TT  4.723 M:      0.0
MESS:128,CHAN:1,DB1:38,DB2:64
MESS:144,CHAN:1,DB1:39,DB2:64
  rtevent:   T  4.747 TT  4.747 M:      0.0
MESS:128,CHAN:1,DB1:39,DB2:64
MESS:144,CHAN:1,DB1:40,DB2:64
  rtevent:   T  4.763 TT  4.763 M:      0.0
MESS:128,CHAN:1,DB1:40,DB2:64
MESS:144,CHAN:1,DB1:41,DB2:64
  rtevent:   T  4.768 TT  4.768 M:      0.0
MESS:128,CHAN:1,DB1:41,DB2:64
MESS:144,CHAN:1,DB1:42,DB2:64
  rtevent:   T  4.805 TT  4.805 M:      0.0
MESS:128,CHAN:1,DB1:42,DB2:64
MESS:144,CHAN:1,DB1:43,DB2:64
  rtevent:   T  4.827 TT  4.827 M:      0.0
MESS:128,CHAN:1,DB1:43,DB2:64
MESS:144,CHAN:1,DB1:44,DB2:64
  rtevent:   T  4.859 TT  4.859 M:      0.0
  rtevent:   T  4.859 TT  4.859 M:      0.0
MESS:128,CHAN:1,DB1:44,DB2:64
MESS:144,CHAN:1,DB1:45,DB2:64
  rtevent:   T  4.864 TT  4.864 M:      0.0
MESS:128,CHAN:1,DB1:45,DB2:64
MESS:144,CHAN:1,DB1:46,DB2:64
  rtevent:   T  4.891 TT  4.891 M:      0.0
  rtevent:   T  4.891 TT  4.891 M:      0.0
MESS:128,CHAN:1,DB1:46,DB2:64
MESS:144,CHAN:1,DB1:47,DB2:64
  rtevent:   T  4.896 TT  4.896 M:      0.0
MESS:128,CHAN:1,DB1:47,DB2:64
MESS:144,CHAN:1,DB1:49,DB2:64
  rtevent:   T  4.917 TT  4.917 M:      0.0
MESS:128,CHAN:1,DB1:49,DB2:64
MESS:144,CHAN:1,DB1:50,DB2:64
  rtevent:   T  4.923 TT  4.923 M:      0.0
  rtevent:   T  4.923 TT  4.923 M:      0.0
MESS:128,CHAN:1,DB1:50,DB2:64
MESS:144,CHAN:1,DB1:51,DB2:64
  rtevent:   T  4.939 TT  4.939 M:      0.0
  rtevent:   T  4.939 TT  4.939 M:      0.0
MESS:128,CHAN:1,DB1:51,DB2:64
MESS:144,CHAN:1,DB1:52,DB2:64
  rtevent:   T  4.955 TT  4.955 M:      0.0
  rtevent:   T  4.955 TT  4.955 M:      0.0
MESS:128,CHAN:1,DB1:52,DB2:64
MESS:144,CHAN:1,DB1:53,DB2:64
  rtevent:   T  4.960 TT  4.960 M:      0.0
MESS:128,CHAN:1,DB1:53,DB2:64
MESS:144,CHAN:1,DB1:54,DB2:64
  rtevent:   T  4.979 TT  4.979 M:      0.0
  rtevent:   T  4.979 TT  4.979 M:      0.0
MESS:128,CHAN:1,DB1:54,DB2:64
MESS:144,CHAN:1,DB1:55,DB2:64
  rtevent:   T  4.992 TT  4.992 M:      0.0
MESS:128,CHAN:1,DB1:55,DB2:64
MESS:144,CHAN:1,DB1:56,DB2:64
  rtevent:   T  5.024 TT  5.024 M:      0.0
MESS:128,CHAN:1,DB1:56,DB2:64
MESS:144,CHAN:1,DB1:57,DB2:64
  rtevent:   T  5.040 TT  5.040 M:      0.0
MESS:128,CHAN:1,DB1:57,DB2:64
MESS:144,CHAN:1,DB1:58,DB2:64
  rtevent:   T  5.051 TT  5.051 M:      0.0
MESS:128,CHAN:1,DB1:58,DB2:64
MESS:144,CHAN:1,DB1:59,DB2:64
  rtevent:   T  5.067 TT  5.067 M:      0.0
MESS:128,CHAN:1,DB1:59,DB2:64
MESS:144,CHAN:1,DB1:60,DB2:64
MESS:128,CHAN:1,DB1:60,DB2:64
MESS:144,CHAN:1,DB1:61,DB2:64

**Comment by vlazzarini** [comment]
Ok, it all looks correct to me, every note on paired with a note off, except for the last one, which looks
like it is hanging (not sure why). Does it play alright on a proper sound-making instrument?

**Comment by genell** [comment]
It might be that I just missed the last line in copying from the command
line output. I'll test with sound now.

**Comment by genell** [comment]
Well, this at least works very well:

<CsoundSynthesizer>
<CsOptions>
-odac    -+rtaudio=jack -+rtmidi=jack -M jack-keyboard:midi_out
</CsOptions>

<CsInstruments>

sr=48000
ksmps=128
nchnls=2
0dbfs=1

massign 1,1

gisine ftgen 0, 0, 2^10, 10, 1

instr 1

icps cpsmidi
asig  poscil .1, icps, gisine
      outs asig, asig

endin

</CsInstruments>
<CsScore>
</CsScore>
</CsoundSynthesizer>

**Comment by vlazzarini** [comment]
ok, that sounds good, i'll keep the ticket open for a bit, in case other issues are found.

**Comment by genell** [comment]
I did a simple stability test just now - I started csound and fed midi (via
jack) to it from a Non Sequencer loop and left town a couple of days. Just
got back, and it was still up and running:
  rtevent:   T238751.115 TT238751.115 M:  0.17965  0.17965
I actually did remember to mute the speakers in my office before leaving...

So I'd say it's fairly stable. Next thing is an automated Cecil Taylor
Test™ of some sort. Maybe fire up another csound instance (or just another
instrument, but I'd rather have them independent) and feed random midi
events from it to the first one via jack. Is there support included in the
recent code for midi-out via jack?

Regards,
Anders

**Comment by genell** [comment]
Well, midi out from csound via jack works fine, and I was able to route
midi from one instance running an adapted version of the second midion
example in the manual (
http://csound.github.io/docs/manual/examples/midion_scale.csd) to another
csound instance listening for jack midi events.

Regards,
Anders

**Comment by genell** [comment]
Btw, maybe there is room for slight improvement in the automatic naming of
devices?

Now, the first instance of csound gets the name "csound-midiout:output" for
midi out and "csound-midi:input" for midi in.
The next gets the name csound-midiout-01 etc. However, the devices are not
named in relation to what instance of csound it is opened from, so if an
input-only instance is started first, and an in-out instance is started
afterwards, there are the two csound-midi and csound-midi-01, but the only
output is csound-midiout without nubering, so it is very hard to figure out
which is which.

I would suggest:
First, name both input and output csound-midi (not csound-midiout) with the
registered ports being either :input or :output
Second, perhaps implement -+jack_midi_client=[client_name],
-+jack_midi_inportname=[input
port name prefix], -+jack_midi_outportname=[output port name prefix]
so that is would be easier to keep track of which is which, even if I
suppose the situation with several csound instances is somewhat uncommon...

Regards,
Anders

**Comment by vlazzarini** [comment]
Ok, thanks for this. I've implemented it, but to do these changes I had to do slight modification on the way clients are open (now both in and out midi ports share the same client). So can you test it is working?
default names would be csound6-midi:input and cound6-midi-output.

**Comment by genell** [comment]
Did you push it? Jack midi behaviour is unchanged after building here...

Regards,
Anders

**Comment by vlazzarini** [comment]
apologies. It's up there now.

**Comment by genell** [comment]
Thanks!
Well, changing the port names works but it seems the changing the device
names doesn't. I still get 'csound-midi' and 'csound-midiout' repectively,
and I get some error/warning messages that I guess might have to do with
the parser?

ALL<ast>
<tree (0x15adca0 : 0x15adb60) type="61" name="=" loc="9:vco2envmidi.csd">
 <treeleft (0x15adb00 : 0x15ada90) type="292" name="SRATE_TOKEN"
loc="8:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15adc40 : 0x15adbd0) type="301" name="INTEGER_TOKEN"
value="48000" loc="8:vco2envmidi.csd">
 </treeright>
</tree>
<treenext (0x15adf10 : 0x15addd0) type="61" name="="
loc="10:vco2envmidi.csd">
 <treeleft (0x15add70 : 0x15add00) type="294" name="KSMPS_TOKEN"
loc="9:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15adeb0 : 0x15ade40) type="301" name="INTEGER_TOKEN"
value="128" loc="9:vco2envmidi.csd">
 </treeright>
</treenext>
<treenext (0x15ae180 : 0x15ae040) type="61" name="="
loc="11:vco2envmidi.csd">
 <treeleft (0x15adfe0 : 0x15adf70) type="295" name="NCHNLS_TOKEN"
loc="10:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15ae120 : 0x15ae0b0) type="301" name="INTEGER_TOKEN"
value="2" loc="10:vco2envmidi.csd">
 </treeright>
</treenext>
<treenext (0x15ae3f0 : 0x15ae2b0) type="61" name="="
loc="12:vco2envmidi.csd">
 <treeleft (0x15ae250 : 0x15ae1e0) type="297" name="ZERODBFS_TOKEN"
loc="11:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15ae390 : 0x15ae320) type="301" name="INTEGER_TOKEN"
value="1" loc="11:vco2envmidi.csd">
 </treeright>
</treenext>
<treenext (0x15ae4c0 : 0x15ae450) type="275" name="T_OPCODE0"
opname0="massign" loc="13:vco2envmidi.csd">
 <treeright (0x15ae590 : 0x15ae520) type="301" name="INTEGER_TOKEN"
value="1" loc="13:vco2envmidi.csd">
 </treeright>
 <treenext (0x15ae660 : 0x15ae5f0) type="273" name="LABEL_TOKEN" label="1"
loc="14:vco2envmidi.csd">
 </treenext>
</treenext>
<treenext (0x15ae800 : 0x15ae730) type="277" name="T_OPCODE" opname="init"
loc="15:vco2envmidi.csd">
 <treeleft (0x15ae7a0 : 0x15ae6c0) type="299" name="T_IDENT"
varname="gasigin" loc="15:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15ae8d0 : 0x15ae860) type="301" name="INTEGER_TOKEN"
value="0" loc="15:vco2envmidi.csd">
 </treeright>
</treenext>
<treenext (0x15b2510 : (nil)) type="287" name="INSTR_TOKEN"
loc="19:vco2envmidi.csd">
 <treeleft (0x15ae9a0 : 0x15ae930) type="301" name="INTEGER_TOKEN"
value="1" loc="20:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15aecb0 : 0x15aebe0) type="277" name="T_OPCODE"
opname="init" loc="20:vco2envmidi.csd">
  <treeleft (0x15aec50 : 0x15aeb70) type="299" name="T_IDENT"
varname="kgain" loc="20:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15aeeb0 : (nil)) type="47" name="/"
loc="21:vco2envmidi.csd">
   <treeleft (0x15aed80 : 0x15aed10) type="302" name="NUMBER_TOKEN"
value="0.500000" loc="20:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15aee50 : 0x15aede0) type="301" name="INTEGER_TOKEN"
value="60" loc="20:vco2envmidi.csd">
   </treeright>
  </treeright>
 </treeright>
 <treenext (0x15af0f0 : 0x15aeb20) type="277" name="T_OPCODE" opname="init"
loc="21:vco2envmidi.csd">
  <treeleft (0x15af090 : 0x15aef10) type="299" name="T_IDENT"
varname="kres" loc="21:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15af170 : 0x15aead0) type="302" name="NUMBER_TOKEN"
value="0.400000" loc="21:vco2envmidi.csd">
  </treeright>
 </treenext>
 <treenext (0x15af360 : 0x15aef60) type="277" name="T_OPCODE"
opname="cpsmidi" loc="22:vco2envmidi.csd">
  <treeleft (0x15af300 : 0x15af220) type="299" name="T_IDENT"
varname="icps" loc="22:vco2envmidi.csd">
  </treeleft>
 </treenext>
 <treenext (0x15af500 : 0x15af270) type="277" name="T_OPCODE"
opname="ampmidi" loc="23:vco2envmidi.csd">
  <treeleft (0x15af4a0 : 0x15aefb0) type="299" name="T_IDENT"
varname="iamp" loc="23:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15af580 : 0x15af000) type="302" name="NUMBER_TOKEN"
value="0.100000" loc="23:vco2envmidi.csd">
  </treeright>
 </treenext>
 <treenext (0x15af8d0 : 0x15af410) type="61" name="="
loc="25:vco2envmidi.csd">
  <treeleft (0x15af710 : 0x15af630) type="299" name="T_IDENT" varname="kcf"
loc="24:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15af870 : (nil)) type="42" name="*"
loc="25:vco2envmidi.csd">
   <treeleft (0x15af790 : 0x15af3c0) type="299" name="T_IDENT"
varname="icps" loc="24:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15af810 : 0x15af5e0) type="301" name="INTEGER_TOKEN"
value="7" loc="24:vco2envmidi.csd">
   </treeright>
  </treeright>
 </treenext>
 <treenext (0x15afc70 : 0x15af680) type="61" name="="
loc="26:vco2envmidi.csd">
  <treeleft (0x15afab0 : 0x15af930) type="299" name="T_IDENT"
varname="kdetune" loc="25:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15afc10 : (nil)) type="47" name="/"
loc="26:vco2envmidi.csd">
   <treeleft (0x15afb30 : 0x15af1d0) type="299" name="T_IDENT"
varname="icps" loc="25:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15afbb0 : 0x15afa20) type="301" name="INTEGER_TOKEN"
value="125" loc="25:vco2envmidi.csd">
   </treeright>
  </treeright>
 </treenext>
 <treenext (0x15afeb0 : 0x15af980) type="277" name="T_OPCODE" opname="vco2"
loc="26:vco2envmidi.csd">
  <treeleft (0x15afe50 : 0x15afcd0) type="299" name="T_IDENT"
varname="asaw1" loc="26:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15aff30 : 0x15af9d0) type="273" name="LABEL_TOKEN"
label="iamp" loc="26:vco2envmidi.csd">
  </treeright>
  <treenext (0x15affb0 : 0x15afdc0) type="273" name="LABEL_TOKEN"
label="icps" loc="27:vco2envmidi.csd">
  </treenext>
 </treenext>
 <treenext (0x15b0280 : 0x15b0060) type="277" name="T_OPCODE" opname="vco2"
loc="27:vco2envmidi.csd">
  <treeleft (0x15b0220 : 0x15afd20) type="299" name="T_IDENT"
varname="asaw2" loc="27:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b0300 : 0x15b00b0) type="273" name="LABEL_TOKEN"
label="iamp" loc="27:vco2envmidi.csd">
  </treeright>
  <treenext (0x15b04b0 : (nil)) type="43" name="+" loc="28:vco2envmidi.csd">
   <treeleft (0x15b0380 : 0x15b0100) type="299" name="T_IDENT"
varname="icps" loc="27:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b0450 : 0x15b03e0) type="299" name="T_IDENT"
varname="kdetune" loc="27:vco2envmidi.csd">
   </treeright>
  </treenext>
 </treenext>
 <treenext (0x15b0b40 : 0x15b0600) type="61" name="="
loc="29:vco2envmidi.csd">
  <treeleft (0x15b0770 : 0x15b0010) type="299" name="T_IDENT"
varname="asaw" loc="28:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b0ae0 : (nil)) type="43" name="+"
loc="29:vco2envmidi.csd">
   <treeleft (0x15b08d0 : (nil)) type="42" name="*"
loc="28:vco2envmidi.csd">
    <treeleft (0x15b07f0 : 0x15b05b0) type="302" name="NUMBER_TOKEN"
value="0.500000" loc="28:vco2envmidi.csd">
    </treeleft>
    <treeright (0x15b0870 : 0x15b0560) type="299" name="T_IDENT"
varname="asaw1" loc="28:vco2envmidi.csd">
    </treeright>
   </treeleft>
   <treeright (0x15b0a80 : (nil)) type="42" name="*"
loc="29:vco2envmidi.csd">
    <treeleft (0x15b0950 : 0x15b0510) type="302" name="NUMBER_TOKEN"
value="0.500000" loc="28:vco2envmidi.csd">
    </treeleft>
    <treeright (0x15b0a20 : 0x15b09b0) type="299" name="T_IDENT"
varname="asaw2" loc="28:vco2envmidi.csd">
    </treeright>
   </treeright>
  </treeright>
 </treenext>
 <treenext (0x15b0df0 : 0x15b0650) type="277" name="T_OPCODE"
opname="madsr" loc="29:vco2envmidi.csd">
  <treeleft (0x15b0d90 : 0x15b0ce0) type="299" name="T_IDENT"
varname="aenv" loc="29:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b0e70 : 0x15afd70) type="302" name="NUMBER_TOKEN"
value="0.100000" loc="29:vco2envmidi.csd">
  </treeright>
  <treenext (0x15b0ef0 : 0x15b0c90) type="302" name="NUMBER_TOKEN"
value="0.001000" loc="29:vco2envmidi.csd">
  </treenext>
  <treenext (0x15b0f70 : 0x15b0c40) type="273" name="LABEL_TOKEN" label="1"
loc="29:vco2envmidi.csd">
  </treenext>
  <treenext (0x15b1040 : 0x15b0fd0) type="302" name="NUMBER_TOKEN"
value="0.100000" loc="29:vco2envmidi.csd">
  </treenext>
 </treenext>
 <treenext (0x15b1340 : 0x15b0bf0) type="277" name="T_OPCODE"
opname="madsr" loc="30:vco2envmidi.csd">
  <treeleft (0x15b12e0 : 0x15b10a0) type="299" name="T_IDENT"
varname="kfenv" loc="30:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b13c0 : 0x15b0ba0) type="302" name="NUMBER_TOKEN"
value="0.600000" loc="30:vco2envmidi.csd">
  </treeright>
  <treenext (0x15b1440 : 0x15b1230) type="302" name="NUMBER_TOKEN"
value="0.001000" loc="30:vco2envmidi.csd">
  </treenext>
  <treenext (0x15b14c0 : 0x15b11e0) type="273" name="LABEL_TOKEN" label="1"
loc="30:vco2envmidi.csd">
  </treenext>
  <treenext (0x15b1540 : 0x15b10f0) type="302" name="NUMBER_TOKEN"
value="0.100000" loc="30:vco2envmidi.csd">
  </treenext>
 </treenext>
 <treenext (0x15b1820 : 0x15b1190) type="277" name="T_OPCODE"
opname="moogladder" loc="31:vco2envmidi.csd">
  <treeleft (0x15b17c0 : 0x15b15a0) type="299" name="T_IDENT"
varname="afilt" loc="31:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b18a0 : 0x15b1140) type="273" name="LABEL_TOKEN"
label="asaw" loc="31:vco2envmidi.csd">
  </treeright>
  <treenext (0x15b1a00 : (nil)) type="42" name="*" loc="31:vco2envmidi.csd">
   <treeleft (0x15b1920 : 0x15b1730) type="299" name="T_IDENT"
varname="kfenv" loc="31:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b19a0 : 0x15b16e0) type="299" name="T_IDENT"
varname="kcf" loc="31:vco2envmidi.csd">
   </treeright>
  </treenext>
  <treenext (0x15b1a80 : 0x15b15f0) type="273" name="LABEL_TOKEN"
label="kres" loc="32:vco2envmidi.csd">
  </treenext>
 </treenext>
 <treenext (0x15b1d30 : 0x15b1690) type="277" name="T_OPCODE"
opname="balance" loc="32:vco2envmidi.csd">
  <treeleft (0x15b1cd0 : 0x15b1ae0) type="299" name="T_IDENT"
varname="asig" loc="32:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b1db0 : 0x15b1640) type="273" name="LABEL_TOKEN"
label="afilt" loc="32:vco2envmidi.csd">
  </treeright>
  <treenext (0x15b1e30 : 0x15b1bd0) type="273" name="LABEL_TOKEN"
label="asaw" loc="33:vco2envmidi.csd">
  </treenext>
 </treenext>
 <treenext (0x15b1b30 : 0x15b1c20) type="275" name="T_OPCODE0"
opname0="out" loc="34:vco2envmidi.csd">
  <treeright (0x15b20d0 : (nil)) type="42" name="*"
loc="34:vco2envmidi.csd">
   <treeleft (0x15b1fc0 : 0x15b1f30) type="299" name="T_IDENT"
varname="kgain" loc="34:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b2070 : 0x15b2020) type="299" name="T_IDENT"
varname="asig" loc="34:vco2envmidi.csd">
   </treeright>
  </treeright>
  <treenext (0x15b22b0 : (nil)) type="42" name="*" loc="35:vco2envmidi.csd">
   <treeleft (0x15b2180 : 0x15b2130) type="299" name="T_IDENT"
varname="kgain" loc="34:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b2250 : 0x15b21e0) type="299" name="T_IDENT"
varname="asig" loc="34:vco2envmidi.csd">
   </treeright>
  </treenext>
 </treenext>
</treenext>
<treenext (0x15b3770 : (nil)) type="287" name="INSTR_TOKEN"
loc="37:vco2envmidi.csd">
 <treeleft (0x15b2590 : 0x15b1e90) type="301" name="INTEGER_TOKEN"
value="99" loc="38:vco2envmidi.csd">
 </treeleft>
 <treeright (0x15b27b0 : 0x15b26e0) type="277" name="T_OPCODE"
opname="init" loc="38:vco2envmidi.csd">
  <treeleft (0x15b2750 : 0x15b2670) type="299" name="T_IDENT"
varname="kgain" loc="38:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b29b0 : (nil)) type="47" name="/"
loc="39:vco2envmidi.csd">
   <treeleft (0x15b2880 : 0x15b2810) type="302" name="NUMBER_TOKEN"
value="0.500000" loc="38:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b2950 : 0x15b28e0) type="301" name="INTEGER_TOKEN"
value="60" loc="38:vco2envmidi.csd">
   </treeright>
  </treeright>
 </treeright>
 <treenext (0x15b2bf0 : 0x15b23b0) type="277" name="T_OPCODE"
opname="reverb" loc="39:vco2envmidi.csd">
  <treeleft (0x15b2b90 : 0x15b2a10) type="299" name="T_IDENT"
varname="arev" loc="39:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b2c70 : 0x15b2360) type="273" name="LABEL_TOKEN"
label="gasigin" loc="39:vco2envmidi.csd">
  </treeright>
  <treenext (0x15b2cf0 : 0x15b2b00) type="273" name="LABEL_TOKEN" label="5"
loc="40:vco2envmidi.csd">
  </treenext>
 </treenext>
 <treenext (0x15b2f60 : 0x15b2d50) type="275" name="T_OPCODE0"
opname0="outs" loc="40:vco2envmidi.csd">
  <treeright (0x15b30c0 : (nil)) type="42" name="*"
loc="40:vco2envmidi.csd">
   <treeleft (0x15b2fe0 : 0x15b2a60) type="299" name="T_IDENT"
varname="kgain" loc="40:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b3060 : 0x15b2ab0) type="299" name="T_IDENT"
varname="arev" loc="40:vco2envmidi.csd">
   </treeright>
  </treeright>
  <treenext (0x15b3270 : (nil)) type="42" name="*" loc="41:vco2envmidi.csd">
   <treeleft (0x15b3140 : 0x15b2e80) type="299" name="T_IDENT"
varname="kgain" loc="40:vco2envmidi.csd">
   </treeleft>
   <treeright (0x15b3210 : 0x15b31a0) type="299" name="T_IDENT"
varname="arev" loc="40:vco2envmidi.csd">
   </treeright>
  </treenext>
 </treenext>
 <treenext (0x15b35a0 : 0x15b2da0) type="61" name="="
loc="42:vco2envmidi.csd">
  <treeleft (0x15b34c0 : 0x15b3410) type="299" name="T_IDENT"
varname="gasigin" loc="41:vco2envmidi.csd">
  </treeleft>
  <treeright (0x15b3540 : 0x15b32d0) type="301" name="INTEGER_TOKEN"
value="0" loc="41:vco2envmidi.csd">
  </treeright>
 </treenext>
</treenext>
</ast>

**Comment by vlazzarini** [comment]
I checked and I had forgotten to change one other bit in the code. 
See how it's doing now.

The warnings might be to do with something else John has been doing in the code (nothing to do with jack).

**Comment by vlazzarini** [comment]
actually there were other mistakes. Fixed now.

**Comment by genell** [comment]
Works like a charm now, thanks!
I'll stress-test it during the afternoon.

Regards,
Anders

**Comment by vlazzarini** [comment]
excellent. Will leave this open until you give it the all-clear.

**Comment by jpffitch** [comment]
Sorry -
i lef tht printout in by mistake.  It was supposed to be protected.  Ignoe 
it until I can fix
==Jofn

**Comment by genell** [comment]
Well, after some stressing, it seems quite stable, but one thing that does
not seem to work like it did before changing the naming abilities is the -M
(or -Q) option. Previously I could get csound to automagically connect to
e.g. the jack virtual keyboard using -M jack-keyboard:midi_out but this
does not work anymore.
I works fine to use the qjackctl connection window to hook the up, so it's
no panic, but it was nice with that functionality...

Regards,
Anders

**Comment by vlazzarini** [comment]
I can fix that. It's an oversight. Give me some time to get round to it (first need to collect daughter from school).

**Comment by genell** [comment]
That's fine, no hurry!
I'll go home and have dinner with my family in the mean time :-)

Regards,
Anders

**Comment by vlazzarini** [comment]
Ok, done (I think). However I had to change slightly the design (with my changes I could not
open input and output together) and so the client/port names have changed slightly. There is one client for input and another for output.

**Comment by genell** [comment]
It's strange that input and output couldn't be opened together when using
the same name - that is what most clients that I have seen do, e.g. the
jack-keyboard.

So, with the current code, I can automatically connect to other midi
clients, and I can name the midi ports, but the midi device names are
static (csound6-midi_in and csound6-midi_out) and cannot be changed. If
that is as intended then all is well!
This was on my laptop at home - I'll test with the desktop that has hosted
all other tests when I get back to the office.

Regards,
Anders

**Comment by vlazzarini** [comment]
Again,  i should be able to fix that. The intention is that you could change the names with the relevant command line option. If it is not working, it is a bug that I need to fix.

It is not that we can't have a single client name, but it is just that it is more awkward, and to me the current code is better, and more efficient, with the separate clients.

**Comment by vlazzarini** [comment]
There was a bug in setting the midi output client, but I fixed it now. Committing to git as we speak.

**Comment by genell** [comment]
Hm, I still can't get it to change client name...
Is it -+jack_midi_client= that should be called or something else?

Regards,
Anders

**Comment by vlazzarini** [comment]
Something else: jack_midi_in_client etc
Check with csound --help

**Comment by genell** [comment]
Ok, back at the office, and the new code works perfectly, thanks!
One thing I was thinking about, though. If I name both the output device
and the input device the same name, there will be a "-01" added to one of
them in the qjackctl connection widow.
As default naming includes "_out" and "_in", is there a way to find if I,
as a particularily daft user, name both input and output clients the same
and in that case append "_out" and "_in" to make it fool proof?


Otherwise, I let the computer run over the weekend sending random midi
events from one instacne to another and it seems rather stable. As can be
seen there were sometimes more than 30 active instances of the instrument
simultaneously, so there is no problem with congestion.
When developing this midi send csd I first managed to loop so that I sent a
new event with the same note before the previous one was turned off,
causing a lot of "overlap" warnings, but it didn't crash, so it is also
quite fault tolerant.

i99    14.00000
  rtevent:   T231442.333 TT231442.333 M:  0.00182  0.00182
 i99     0.00000
  rtevent:   T231442.779 TT231442.779 M:  0.00104  0.00104
 i99    14.00000
  rtevent:   T231442.915 TT231442.915 M:  0.00152  0.00152
  rtevent:   T231442.984 TT231442.984 M:  0.00111  0.00111
 i99    32.00000
 i99    18.00000
  rtevent:   T231443.661 TT231443.661 M:  0.00174  0.00174
 i99     0.00000
  rtevent:   T231443.995 TT231443.995 M:  0.00135  0.00135
 i99    14.00000
  rtevent:   T231445.163 TT231445.163 M:  0.00189  0.00189
  rtevent:   T231445.240 TT231445.240 M:  0.00116  0.00116
 i99    17.00000
 i99     3.00000
  rtevent:   T231445.496 TT231445.496 M:  0.00064  0.00064
 i99     0.00000
  rtevent:   T231445.824 TT231445.824 M:  0.00076  0.00076
 i99     7.00000
  rtevent:   T231447.040 TT231447.040 M:  0.00114  0.00114
 i99     0.00000
  rtevent:   T231447.264 TT231447.264 M:  0.00064  0.00064
 i99    10.00000
  rtevent:   T231448.736 TT231448.736 M:  0.00117  0.00117
 i99     0.00000
  rtevent:   T231449.579 TT231449.579 M:  0.00060  0.00060
 i99    10.00000
  rtevent:   T231450.112 TT231450.112 M:  0.00165  0.00165
 i99     0.00000


Regards,
Anders

**Comment by vlazzarini** [comment]
alternatively, I can use just a single client prefix, and add _in and _out to it, would that be better?

**Comment by genell** [comment]
That would work perfectly, I think!

**Comment by vlazzarini** [comment]
done. -+jack_midi_client=midisynth  will yield midisynth_in:port and midisynth_out:port  client:port names. 
Default is csound6-midi{_in,_out}

**Comment by genell** [comment]
With +jack_midi_client=cs6synth I get cs6synth_out and cs6synth_out_in
so there might be something slightly off with the appending?

**Comment by vlazzarini** [comment]
ops, forgot about that case of opening in and out together. fixed now

**Comment by genell** [comment]
Works flawlessly, thank you!

I'd say it would be ok to close the ticket now, but I have only been
testing on linux. I would have given it a go on Windows, but I can't get
past the hassle of building csound on Windows, so I am of very little help
there...

Regards,
Anders

**Comment by vlazzarini** [comment]
Jack on windows? I never realised it was possible. Anyway, I will close this now,

**Comment by genell** [comment]
Well, "possible" in a loose sense :-)  -
http://jackaudio.org/faq/jack_on_windows.html
I can give it a shot after Mike have whipped together an installer for the
next csound release...
