### ISSUE TITLE
linsegb bug when re-using an instance

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#801]
this is a simple example (the second call could also be left out)

instr 1
kenv linsegb 0, 0.25, .2, 1, 0
asig poscil kenv, 400
     outs asig, asig
endin
schedule 1, 0.0, 1 ;first instance
schedule 1, 0.5, 1 ;second instance - ok
schedule 1, 1.1, 1 ;re-using first instance - "Breakpoint 0 not valid"

the error message is:
INIT ERROR in instr 1: Breakpoint 0 not valid
kenv	linsegb	0	0.25	.2	1	0	
		   T  1.100 - note deleted.  i1 had 1 init errors

**Comment by vlazzarini** [comment]
Found the bug. It's been there since Csound 5 at least (probably earlier). I'm surprised it ever
worked. A real howler. I will need to check the other breakpoint opcodes to see if they have
the same problem.

**Comment by signalsender103** [comment]
It's unclear to me from your code how you're reusing instances of linsegb.

**Comment by vlazzarini** [comment]
fixed in git.

@signalsender103 : when two instances of an instrument do not overlap, memory of the previous instance is re-used (no new alloc is made).

**Comment by joachimheintz** [comment]
the bug is still there, and i don't see your commit when i pull.
maybe you forgot to push?

**Comment by vlazzarini** [comment]
yeah, forgot to push.

**Comment by joachimheintz** [comment]
yes, works now =)
