### ISSUE TITLE
Compiling CSD with commented-out </CsInstruments> tag causes segfault

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#830]
On macOS, running

```csound-csd
<CsoundSynthesizer>
<CsInstruments>
scoreline_i "e"
/*
</CsInstruments>*/
</CsInstruments>
</CsoundSynthesizer>
```

using `csound --nosound test.csd` causes a segfault:

```
virtual_keyboard real time MIDI plugin for Csound
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
--Csound version 6.09.1 (double samples) Jul 10 2017 
[commit: 0815e64648cdd7497c97d6a82eeffbcc774596a8]
libsndfile-1.0.25
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjacko.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjackTransport.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)
UnifiedCSD:  test.csd
STARTING FILE
Creating orchestra
unknown CSD tag: </CsInstruments>

scoreless operation
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled

csound command: Segmentation fault
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.251s, CPU: 0.001s
no sound written to disk
```

**Comment by vlazzarini** [comment]
Seems to be an error in the CSD reading code.

**Comment by jpffitch** [comment]
On Linux I see no cras

irtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
--Csound version 6.09.1 (double samples) Jul 23 2017
[commit: 50ed7073e69d0336abc8c571f8076ff09dcee4cd]
libsndfile-1.0.29pre1
Reading options from $HOME/.csound6rc
Reading options from local directory .csound6rc
UnifiedCSD:  bw.csd
STARTING FILE
Creating orchestra
unknown CSD tag: </CsInstruments>

scoreless operation
rtmidi: ALSA Raw MIDI module enabled
rtaudio: pulseaudio module enabled
unexpected EOF!
cannot compile orchestra
end of score.              overall amps:      0.0
            overall samples out of range:        0
2 errors in performance
Elapsed time at end of performance: real: 0.000s, CPU: 0.000s

**Comment by jpffitch** [comment]
hat happes is tat it looks for te instrument section wic is

<CsInstruments>
scoreline_i "e"
/*
</CsInstruments>*/

so nexpeted EOF; ot sure wy MaOS differs

**Comment by vlazzarini** [comment]
Even without the crash, CSD reading was not dealing properly with some comments. 
I push a fix. Can you test it on Linux?

**Comment by jpffitch** [comment]
Codeoks rigt but what about te score section?  ad oters?

**Comment by jpffitch** [comment]
Sorry; should added that it does not deal with

...
aot oscil 1,440  /* but not yet
</CsInstruments>
*/
endin
.....

**Comment by nwhetsell** [comment]
I suspect there are also issues with things like

```csound-csd
<CsoundSynthesizer>
<CsInstruments>
scoreline_i "e"
prints {{
</CsInstruments>}}
</CsInstruments>
</CsoundSynthesizer>
```

If it’s any help, a similar problem arises when putting JavaScript in XHTML documents. The typical workaround is to use CDATA sections—

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head><title /></head>
<body>
<script type="text/javascript">
  //<![CDATA[
  /*
  </not-an-end-tag>
  */`
  </also-not-an-end-tag>`
  //]]>
</script>
</body>
</html>
```

—but I don’t think there’s a similar mechanism in Csound.

**Comment by vlazzarini** [comment]
yes, I did not test all cases. It seemed to work in the instances I did, but might implementation is a bit ad hoc so it might not ideal. 

There was existing code to deal with comments in <CsOptions>, maybe it could be re-used. So it's only CsInstruments and CsScore that need to be dealt with.

**Comment by jpffitch** [comment]
Fixed in git, and other cases (strigs0 and also score cases

**Comment by nwhetsell** [comment]
Even after ad366d35d391cd342b633a4c2d0aa990dc80d2ff, it appears there’s still an issue with strings that contain line continuations. On macOS, running

```csound-csd
<CsoundSynthesizer>
<CsInstruments>
scoreline_i "e"
prints "\
</CsInstruments>\n"
</CsInstruments>
</CsoundSynthesizer>
```

using `csound --nosound test.csd` outputs

```
0dBFS level = 32768.0
--Csound version 6.09.1 (double samples) Jul 31 2017 
[commit: 840f2814f6a5060ca88eb145a0960f09a9cbc5d5]
libsndfile-1.0.28
UnifiedCSD:  test.csd
STARTING FILE
Creating orchestra
missing " to terminate string
unknown CSD tag: </CsInstruments>\n"

unknown CSD tag: </CsInstruments>

Reading CSD failed ... stopping
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.000s, CPU: 0.000s
no sound written to disk
```

Running the orchestra alone using `csound --nosound --orc test.orc` prints `</CsInstruments>` as expected.

It may be worth using a Flex lexer to read CSD files.

**Comment by jpffitch** [comment]
was ot aware tat we allowed tat bt today's fix was supposed to deal with 
tat
y

**Comment by nwhetsell** [comment]
For what it’s worth, line continuations in strings were part of issue #660.
