### ISSUE TITLE
bug(s) in r score statement

### ISSUE THREAD

**Issue by luisjure** [csound/csound#878]
hi, the csd below discloses several bugs in the r score statement:

- the duration of the section (s 6) is not observed
- in the first pass the tempo indication has no effect
- in the last pass the tempo indication has no effect and p-fields are not parsed correctly
- the section after the repetitions is not performed 

the bugs were introduced in 6.09 and persist until now in git.
the orchestra compiles fine in 6.08.

<CsoundSynthesizer>
<CsInstruments>

sr	=	48000
ksmps	=	1
0dbfs	=	1

instr 1	

idur	=	p3
iamp	=	ampdbfs(-6)
print	p4
ifreq	=	cpsmidinn(p4)
idec	=	0.05

kamp	linen	iamp, 0, idur, idec
asig	pluck	kamp, ifreq, ifreq, 0, 1

	out	asig

endin

</CsInstruments>
<CsScore>

r	4
t	0	120
i1	0	.5	60
i1	1	.	62
i1	2	.	64
i1	3	.	65
s	6

t	0	240
i1	0	.8	69
i1	1	.	71
i1	2	.	72
e
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
Two unrelated bugs

1) Format "s 6" is just not being recognised and the 6 is treated as a new opcode

2) There is a missing newline in the output of r from csound_prs.lex

**Comment by jpffitch** [comment]
Fixed error #2 but failed to fix #1 so far

**Comment by jpffitch** [comment]
Believed fixed in git now.

**Comment by luisjure** [comment]
Most bugs are indeed resolved, thank you!
One problem remains, though: the "s" statement is not included in the repetition. Although this is not explicit in the manual, that's how 6.08 behaved and it's what I would expect. I definitely get a different result now that until 6.08. Any comments?

**Comment by jpffitch** [comment]
Not sure what you mean.  If you still have a 6.08 found could you run your .csd with -t0 option and send me the score.srt file it generates?  That would let me see what you expect.

⁣Sent from TypeApp ​

**Comment by luisjure** [comment]
el 2017-11-21 a las 17:22 John ffitch escribió:

> Not sure what you mean.  If you still have a 6.08 found could you run
> your .csd with -t0 option and send me the score.srt file it generates?
> That would let me see what you expect.




-- 
luis jure
eMe - estudio de música electroacústica
http://www.eumus.edu.uy/eme/
http://www.eumus.edu.uy/docentes/jure/

**Comment by luisjure** [comment]
i 1 0.000000 0.000000 0.500000 0.250000 60
i 1 1.000000 0.500000 0.500000 0.250000 62
i 1 2.000000 1.000000 0.500000 0.250000 64
i 1 3.000000 1.500000 0.500000 0.250000 65
f 0 6.000000 3.000000
s
w 0 120
i 1 0.000000 0.000000 0.500000 0.250000 60
i 1 1.000000 0.500000 0.500000 0.250000 62
i 1 2.000000 1.000000 0.500000 0.250000 64
i 1 3.000000 1.500000 0.500000 0.250000 65
f 0 6.000000 3.000000
s
w 0 120
i 1 0.000000 0.000000 0.500000 0.250000 60
i 1 1.000000 0.500000 0.500000 0.250000 62
i 1 2.000000 1.000000 0.500000 0.250000 64
i 1 3.000000 1.500000 0.500000 0.250000 65
f 0 6.000000 3.000000
s
w 0 240
i 1 0.000000 0.000000 0.800000 0.200000 69
i 1 1.000000 0.250000 0.800000 0.200000 71
i 1 2.000000 0.500000 0.800000 0.200000 72
e
e

**Comment by jpffitch** [comment]
Ary!  I misunderstood the meaning of s.  I thought it was a start of a section not the end.  May take a little time to rewrite.

⁣Sent from TypeApp ​

**Comment by luisjure** [comment]
I'm sorry I wasn't clear before, not sure how to explain it in different words.

What I mean is that the "r" statement used to repeat the whole section, including the duration extended by the "s" statement. And although that behaviour is not explicitly described in the manual, it was what I would expect.

Now "r" only cycles through the notes, and does not repeat the whole section, that would include the duration of p1 in the s statement. (Yes, I know that now "s" interprets p1 in a different way than before.)

I hope it's a bit less confusing now.

**Comment by luisjure** [comment]
Sorry, I posted the last comment before seeing your message.

**Comment by jpffitch** [comment]
All my confusion.  Think it is fixed now in git -- please try

**Comment by luisjure** [comment]
Yes! Now it's perfect.

But now for some reason compilation now it fails on my Gentoo machine, because it can't find Fl.H.
It was working earlier, I guess I should open another issue.
